export const metadata = {
    title: 'About Page',
    description: 'Generated by create next app',
}


export default function layout({children}) {
  return (
    <>
     <div>{children}</div>
    </>
    
  )
}
